### ISSUE TITLE
Easily add media/files to site - possibly use IMCE as interim solution?

### ISSUE THREAD

**Issue by tobybellwood** [govCMS/govcms8-installer#10]
Looking at the Drupal 8.5/8.6 roadmap, it seems having a coherent ecosystem for browsing and adding media is still a way off (https://www.drupal.org/core/roadmap#media).

There is some work being done to split out functionality from Lightning (https://www.drupal.org/project/lightning_media), but it still depends on lightning_core atm.

I propose that we use an interim/alternate solution until Media can be fully used natively in core to provide the optimal experience to our users.

One solution already suggested is IMCE (https://www.drupal.org/project/imce)

**Comment by gargsuchi** [comment]
In one of our projects, we are using lightning_media - which uses media core now. 
Plan to extract ourselves out of lightning soon. Will post the findings here.

**Comment by tobybellwood** [comment]
Thanks @gargsuchi - we're keeping a close eye on lightning media too - let us know how you go!

**Comment by rooby** [comment]
Although media is not ready for prime-time yet, I'm a little hesitant in regards to starting with IMCE (or other) and then switching to media later, unless we can ensure that any changes we make later will not break old sites that use IMCE (or cause administration headaches related to having content with two different types of embedding).

Taking D7 GovCMS as an example, I expect minimal ability to mess with the selection of modules once it has undergone security assessment and is being used by live sites.

The forecasted date for media WYSIWYG of March 2019 is not great though. waiting for that would mean likely not being ready until EOFY 2019. Not sure how far behind the current plan that would be.

I guess if it continued to ship with IMCE (or other) after the media solution is in and there was no upgrade path from old to new media system for existing GovCMS sites, that would probably be a workable scenario.

**Comment by murraywoodman** [comment]
Now that Media is in core it is perhaps time to revisit this issue. I think that it is important to get Media working as part of the initial release. This has a big impact on the fields GovCMS8 ships with for Featured Images etc. It is important to get this in place from the get go. There are a number of options out there for Media setup such as Lightning (already mentioned), Thunder (I haven't looked at the inner workings but the demos look good), PNX Media (which I know you are aware of) and a home grown solution.

The key is that the correct field type is in place at the start and then the configuration around that field (media browsers and the like) can be fine tuned and improved overtime. Theoretically the only change for early adopters would be config rather than a content migration.

**Comment by klonos** [comment]
Yep, definitely worth a revisit. Especially now that 8.6 has been released.

**Comment by murraywoodman** [comment]
This issue was initially around using Media, rather than Files. The initial config in GovCMS8 was using Files and then the switch was made to using Media. So now we have Media for Featured Image and Thumbnail. That was a win. 

However, now that Media is stable in core things are moving on some more. There is another related issue https://github.com/govCMS/govCMS8/issues/118 where Media in core is being discussed in relation to Remote Video.

**Comment by tobybellwood** [comment]
Definitely - the need for IMCE seems to have dissipated with the introduction of core media

**Comment by simesy** [comment]
Please re-open if needed.
