### ISSUE TITLE
Composer update is copying files unnecessarily

### ISSUE THREAD

**Issue by imperator99** [govCMS/govcms8-installer#12]
Hi,
When I run 'composer update', something in the post update script is copying over files from my root folder (such as my Circle CI config and cloud foundry manifest files) into docroot/profiles/govcms.
This doesn't seem necessary or useful and I need to keep removing them to make sure they don't make it into the cloud foundry app itself.
Thanks,
Jesse.

**Comment by imperator99** [comment]
I discovered it is the <rsync> element in build.xml. The solution was to add my particular files into the list of exclusions (no spaces after commas).
I'm not sure if there is a better solution, and I don't know where the build.xml file comes from. If it is automatically generated then I presume at some point it may get overwritten.

**Comment by pandaskii** [comment]
Build.xml  check line 79-89 - this file is hardcoded for phing

https://github.com/govCMS/govCMS8/blob/1.x/build.xml

```
  <!-- Push the govcms profile into the Drupal code base. -->
  <target name="push" depends="env">
    <!-- Create the destination if it doesn't exist. -->
    <mkdir dir="${profile}"/>
    <!-- rsync the profile, excluding developer flotsam. -->
    <filesync destinationDir="${profile}" rsyncPath="${rsync}" sourceDir="." verbose="false" exclude=".idea,bin,build.xml,.git,.gitignore,${docroot},karma.conf.js,*.make,node_modules,.travis.yml,vendor"/>
  </target>
```

Shall we create an ignore file and generate a list of the exclude?

**Comment by imperator99** [comment]
What would cause the build.xml to be overwritten? Is it easier to change the `<rsync>` element or an ignore file? I mean, if you're installing GovCMS like this anyway you're already in the weeds.

**Comment by imperator99** [comment]
Or... can it do an include, so it only includes the files that need to be included? I have zero experience with phing so I don't know what's possible.

**Comment by pandaskii** [comment]
The idea is to sync the govCMS profile to docroot every time after the "composer update"  - a "push" that we defined, this can keep up and update the docroot govCMS profile up-to-date easily. 

This is the root reason that files are copied unnecessarily. In most cases, gitignore can be used to keep the govCMS profile under docroot clean. Unfortunately, this may not be always the solution.

An exclude list is easier instead of an include list in this action. I would like to introduce an exclude file https://github.com/govCMS/govCMS8/blob/1.x/build/config/sync.push.exclude.txt with latest 1.x codebase update.

**Comment by simesy** [comment]
Appears to be resolved.
