### ISSUE TITLE
Build PR testing platform

### ISSUE THREAD

**Issue by tobybellwood** [govCMS/govcms8-installer#15]
Investigate using current Jenkins to build PR environments for testing.

**Comment by klonos** [comment]
FYI. Tugboat has an offering for providing their service for free for OSS: https://tugboat.qa/pricing

mailto:support@tugboat.qa?subject=Sponsorship

Examples: https://github.com/TugboatQA
Documentation on setup: https://docs.tugboat.qa/tutorials/drupal8

There is an API available so that no PRs are required (i.e. can be used to spin up demo sites a-la simplytest.me)

**Comment by simesy** [comment]
I dare say this is done, and even ended up being tugboat.
