### ISSUE TITLE
 Chosen JavaScript file Not Installed

### ISSUE THREAD

**Issue by monymirza** [govCMS/govcms8-installer#346]
On fresh install, Status report shown that Chosen JavaScript file missing. PFA

![Screenshot_2019-10-28 Status report City West Water(1)](https://user-images.githubusercontent.com/18459632/67646847-bbcdba80-f951-11e9-9f57-b71ef24878ef.png)

**Comment by pandaskii** [comment]
This issue could happen if you use the Drupal.org tarball file for installation.

It is an issue with `Chosen` module and can be fixed by moving the folder `libraries` in the project root

https://www.drupal.org/project/chosen/issues/2915592

in Drupal 8, few modules cannot detect the library correctly if the library in a different location.
