### ISSUE TITLE
Permissions by Term module is pinned to version 2.12 - should be pinned on minor version only

### ISSUE THREAD

**Issue by jepster** [govCMS/govcms8-installer#506]
Hi,

I am the maintainer of the Permissions by Term module and very glad, that you are using my module in Australia. :) 

The composer.json file pins the Permissions by Term module to version 2.12. That version is old. There should be a constraint on the minor version only (for Drupal 8 it's ^2.0). If you pin the minor version, you will receive the latest patch versions with bug- and security fixes. There are bugfixes and improved features (like setting PbT for specific taxonomy vocabularies only). Is there any reason for pinning the version? Can I help?

**Comment by jepster** [comment]
I am already waiting since 3 weeks for a reply. Would you please answer?

**Comment by fubarhouse** [comment]
@pandaskii, @thisisalistairsaccount ^^

**Comment by jepster** [comment]
No updates since two months. Do you still maintain govCMS?

**Comment by pandaskii** [comment]
@jepster 

Here is a community `issues` channel, and there is no such person who read and reply to every issue:)

If you need contact GovCMS urgently, please visit this URL https://www.govcms.gov.au/contact-us

GovCMS is a distribution uses fixed versions of the modules/themes/libraries which the corresponding version was tested with. This prevents bugs introduced by version differences, dependency-related troubles and keeps the distribution in a stable and secure status.

**Comment by jepster** [comment]
If you are pinning the version of every module (like here https://github.com/govCMS/GovCMS8/blob/1.x/composer.json), then the users are getting not even the patch versions. That means that they are not receiving any security fixes.

Your user's software is based on totally dangerous software packages. As I am the maintainer of the Permissions by Term Drupal module, I know, that you are missing at least security patches in the Permissions by Term Drupal module. Your distribution is based on many more modules which do not receive security patches by your current composer.json file definition.

I am not sure, if you are aware of semantic versioning and patch version constraints (https://getcomposer.org/doc/articles/versions.md).

**Comment by klonos** [comment]
@jepster thanks for the time/effort in maintaining the PbT module 🙏 ...the versions of modules included in the GovCMS distribution are pinned because we need to do **controlled** rollouts for 100s of government sites which are hosted on the GovCMS SaaS platform at the same time. One such release is scheduled tomorrow actually, to update customers still on GovCMS7: https://status.govcms.support/incidents/fp123qv5dvfm ...this release includes the recent security updates for Drupal core, and the rollout of the respective GovCMS8 update will follow shortly after.

> Your user's software is based on totally dangerous software packages

Sorry, but this is a totally unfair statement to make. Can you please point out which packages you are referring to?

> As I am the maintainer of the Permissions by Term Drupal module, I know, that you are missing at least security patches in the Permissions by Term Drupal module.

The last security release for PbT according to https://www.drupal.org/project/permissions_by_term/releases was 8.x-2.11, and the version currently included in the GovCMS distro is 8.x-2.12 (see https://github.com/govCMS/GovCMS8/blob/1.x/composer.json#L89). If you as a maintainer have released a security fix for any versions after that, then you must have failed to flag it as such I'm afraid, so it did not hit our radars. Can you please clarify?

> Your distribution is based on many more modules which do not receive security patches by your current composer.json file definition.

I think that once again you are mistaken here, but if I am wrong, can you please point those modules and security updates to us?

> I am not sure, if you are aware of semantic versioning and patch version constraints

Sorry Peter, but you seem to be upset for some reason, and I personally think that your tone is not in par with the Drupal community code of conduct, nor with how open source communities work. I think that you should revisit https://www.drupal.org/dcoc and have a careful read through it.

Thanks
